[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name= "tinylist"
version = "0.1.0"
description= "A handmade dynamic array"
requires-python = ">=3.8"

[tool.setuptools]
packages=["tinylist"]