name: CI 

on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install -e .
      - run: pip install pytest mypy ruff
      - run: ruff check tinylist
      - run: ruff format --check tinylist
      - run: mypy --strict tinylist
      - run: pytest tests/ -v --cov=tinylist --cov-reprt=term
      